// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelOptimizer.Persistence;

#nullable disable

namespace TravelOptimizer.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625210438_AddSegmentCoordinates")]
    partial class AddSegmentCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasCoordinates")
                        .HasColumnType("boolean");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" <> ''");

                    b.HasIndex("UserId", "StartUtc");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.CorridorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CorrectionFactor")
                        .HasColumnType("double precision");

                    b.Property<string>("CorridorKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HourBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Mape")
                        .HasColumnType("double precision");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Mode", "CorridorKey", "DayType", "HourBucket")
                        .IsUnique();

                    b.ToTable("CorridorModels");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.CorridorSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("CorridorKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disruptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HourBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PredictedDurationMin")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SampledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WaitMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorridorKey", "Mode", "SampledAt");

                    b.ToTable("CorridorSamples");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.GoogleCalendarConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GoogleCalendarConnections");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.LegOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ActualDurationMin")
                        .HasColumnType("integer");

                    b.Property<bool>("ArrivedOnTime")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TravelDecisionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TravelDecisionId")
                        .IsUnique();

                    b.ToTable("LegOutcomes");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.PolicyWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key", "IsActive");

                    b.ToTable("PolicyWeights");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.PredictionSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMin")
                        .HasColumnType("integer");

                    b.Property<string>("FromLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("FromLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("FromLng")
                        .HasColumnType("double precision");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ToLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("ToLng")
                        .HasColumnType("double precision");

                    b.Property<int>("TravelPredictionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TravelPredictionId", "Order");

                    b.ToTable("PredictionSegments");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.ProposedAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ShadowImprovementMin")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("ProposedAdjustments");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.SourceHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgMape")
                        .HasColumnType("double precision");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DisabledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EwmaSuccessRate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Mode")
                        .IsUnique();

                    b.ToTable("SourceHealth");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChosenMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PredictedArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PredictedWastedMin")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecommendedDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TravelLegId")
                        .HasColumnType("integer");

                    b.Property<bool>("WasExploration")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TravelLegId")
                        .IsUnique();

                    b.ToTable("TravelDecisions");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArriveBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorridorKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FromLat")
                        .HasColumnType("double precision");

                    b.Property<double>("FromLng")
                        .HasColumnType("double precision");

                    b.Property<string>("HourBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ToLat")
                        .HasColumnType("double precision");

                    b.Property<double>("ToLng")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("TravelLegs");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalibratedDurationMin")
                        .HasColumnType("integer");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disruptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Feasible")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RawDurationMin")
                        .HasColumnType("integer");

                    b.Property<int>("TravelLegId")
                        .HasColumnType("integer");

                    b.Property<int>("WaitMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TravelLegId");

                    b.ToTable("TravelPredictions");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.CalendarEvent", b =>
                {
                    b.HasOne("TravelOptimizer.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.GoogleCalendarConnection", b =>
                {
                    b.HasOne("TravelOptimizer.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.LegOutcome", b =>
                {
                    b.HasOne("TravelOptimizer.Domain.Entities.Travel.TravelDecision", "TravelDecision")
                        .WithOne("Outcome")
                        .HasForeignKey("TravelOptimizer.Domain.Entities.Travel.LegOutcome", "TravelDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelDecision");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.PredictionSegment", b =>
                {
                    b.HasOne("TravelOptimizer.Domain.Entities.Travel.TravelPrediction", "TravelPrediction")
                        .WithMany("Segments")
                        .HasForeignKey("TravelPredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPrediction");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelDecision", b =>
                {
                    b.HasOne("TravelOptimizer.Domain.Entities.Travel.TravelLeg", "TravelLeg")
                        .WithOne("Decision")
                        .HasForeignKey("TravelOptimizer.Domain.Entities.Travel.TravelDecision", "TravelLegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelLeg");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelLeg", b =>
                {
                    b.HasOne("TravelOptimizer.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelPrediction", b =>
                {
                    b.HasOne("TravelOptimizer.Domain.Entities.Travel.TravelLeg", "TravelLeg")
                        .WithMany("Predictions")
                        .HasForeignKey("TravelLegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelLeg");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelDecision", b =>
                {
                    b.Navigation("Outcome");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelLeg", b =>
                {
                    b.Navigation("Decision");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("TravelOptimizer.Domain.Entities.Travel.TravelPrediction", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
